version: "3.8"
services:

    # PHP Service
    php:
        container_name: php
        build:
            context: .
            target: php
        environment:
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - mysql
    # Mysql Server
    mysql:
        image: mysql:8.0.32
        ports:
        - 3306:3306
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: local
        volumes:
        - db-data:/var/lib/mysql
    # Redis Server
    redis:  
        image : redis:alpine
        command: redis-server --appendonly yes --requirepass local
        ports: 
        - 6379:6379

volumes:
    db-data: ~
